### ISSUE TITLE
Minimal port of `pybullet-drones`

### ISSUE THREAD

**Issue by hidal00p** [hidal00p/i-hate-drones#2]
To avoid building two projects, and also not to inherit all the files from the `pybullet-drones` we would like to port only the minimal viable portion.

**Port ...**:
- [x] PID control logic.
- [x] Velocity aviary.
- [x] A digital twin `.urdf` model.

**Comment by ankovalov** [comment]
Solved by this [commit](https://github.com/hidal00p/i-hate-drones/commit/16e9b31d5acbda9343fc5df8467e1413fa01ffb1).
