### ISSUE TITLE
Demo of navigation along a generated curve

### ISSUE THREAD

**Issue by hidal00p** [hidal00p/i-hate-drones#3]
Generate a curve and make drone follow it:

- [x] Some periodic curve
- [ ] ~~Ellipsoid~~
- [ ] ~~Arbitrary bezier~~

**UPD**
Bezier curve generation will probably be an add-on, since I do not have time to prioritize it atm.

**Comment by ankovalov** [comment]
**UPD**
Look at the demo in gym-pybullet repo. The core question is: how are the inputs provided to the aviaries?

Once I know that, I can start thinking how do I want to adapt that to meet my needs.
