### ISSUE TITLE
Port ray tracing sensor

### ISSUE THREAD

**Issue by hidal00p** [hidal00p/i-hate-drones#5]
- [x] Port sensor logic, i.e. usage of pybullet ray tracing for object detection.
- [ ] ~~Conditionally add it to the observation space (e.g. controlled by `with_vision` parameter)~~

**Comment by ankovalov** [comment]
Currently blocked by this [issue](https://github.com/users/hidal00p/projects/1/views/1?pane=issue&itemId=68824716).

**Comment by ankovalov** [comment]
I will try to make a sensor activation function a bit better, than just having a distance value in there. Most likely will just use shifted sigmoid.
