### ISSUE TITLE
Allow to have specific flight scenarious

### ISSUE THREAD

**Issue by hidal00p** [hidal00p/i-hate-drones#7]
Right now objects and targets are generated at random. it would be interesting to be able to generate flight environments with fixed conditions, i.e. single obstacle placed midway between a drone and a target.

**Comment by ankovalov** [comment]
This was essentially solved while developing the demo for eyes (ray tracing based sensor) + trajectory generation mechanism.

Hence, now a flight scenario can be developed, such that an obstacle is placed somewhere on the path, which a quad seeks to follow.
