### ISSUE TITLE
Deploy the training onto the cluster

### ISSUE THREAD

**Issue by hidal00p** [hidal00p/i-hate-drones#9]

**Comment by ankovalov** [comment]
**UPD**:
- First test run submitted to an exclusive execution, however, it has not been picked up yet.
- Next step would be to submit a full run to the cluster. 10 CPUs 2.5 mln timesteps.
- I am still not sure how to best handle parallelization.

**Comment by ankovalov** [comment]
**UPD:**

- I bailed on trying to get an exclusive node, since the priority list is too large. Maybe it will be picked up at night.
- Atm running a 3h quota.
- But ofc this currently does not scale well, so I need to add command line arguments via which the training runtime will be configured.

**Comment by ankovalov** [comment]
**UPD**:
- It is actually insane than on an exclusive node, whatever did not complete in 6h in 14 threads is completed in ~14min...
- Environment successfully running on the cluster.
- First mode trained. It is, however, unsuccessful.
